version: '3.3'
services:
  AN:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    
    image: an
    container_name: an-container
    working_dir: /projectAN/
    privileged: true
    command: >
      sh -c "python3 projectAN/manage.py makemigrations AN likeAN priceInfo socialUser
      && python3 projectAN/manage.py migrate
      && gunicorn --workers 3 --bind 0.0.0.0:5000 --preload --chdir ./projectAN projectANConfig.wsgi.prod:application"

    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET_KEY
      - STATE
      - DJANGO_SETTINGS_MODULE
      - GOOGLE_OAUTH2_CLIENT_ID
      - GOOGLE_OAUTH2_CLIENT_SECRET
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - default
      - an_network

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.7.14-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    container_name: celery_container
    image: an
    working_dir: /projectAN/
    command: >
      sh -c "cd projectAN && ls -a"
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET_KEY
      - STATE
      - DJANGO_SETTINGS_MODULE
      - GOOGLE_OAUTH2_CLIENT_ID
      - GOOGLE_OAUTH2_CLIENT_SECRET
    depends_on:
      - AN
      - chrome
    links:
      - chrome
  
  chrome:
    image: selenium/standalone-chrome:4.0.0-rc-1-prerelease-20210618
    expose:
      - "4444"
    ports:
      - "7900:7900"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 80M
        reservations:
          cpus: "0.01"
          memory: 50M

  nginx-proxy:
    build:
      context: .
      dockerfile: ./dockerfiles/DockerNginx
    image: nginx-proxy
    container_name: nginx-proxy-container
    privileged: true
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - /var/lib/jenkins/workspace/ANPipeline_master/static_in_env:/static
    links:
      - AN
    depends_on:
      - AN
networks:
  an_network:
    driver: bridge