version: '3.3'
services:
  AN:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    
    image: an
    container_name: an-container
    volumes:
      - /var/lib/jenkins/workspace/ANPipeline_master:/projectAN/
      - /var/lib/jenkins/workspace/ANPipeline_master/gunicorn:/etc/systemd/system/
    working_dir: /projectAN/
    command: >
      bash -c "python3 projectAN/manage.py makemigrations AN likeAN priceInfo socialUser
      && python3 projectAN/manage.py migrate
      && echo "yes" | python3 projectAN/manage.py collectstatic
      && sudo systemctl enable gunicorn.services
      && sudo systemctl stop gunicorn
      && sudo systemctl start gunicorn.socket
      && sudo systemctl start gunicorn"
    
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET_KEY
      - STATE
      - DJANGO_SETTINGS_MODULE
      - GOOGLE_OAUTH2_CLIENT_ID
      - GOOGLE_OAUTH2_CLIENT_SECRET
    ports:
      - "5000:5000"
    expose:
      - "5000"


  nginx:
    image: nginx
    container_name: nginx-container
    build:
      context: .
      dockerfile: ./dockerfiles/DockerNginx
    
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - /var/lib/jenkins/workspace/ANPipeline_master/static_in_env:/static
    links:
      - AN
    depends_on:
      - AN